name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore engine dependencies
      run: dotnet restore ./ExtraChess/ExtraChess.csproj
    - name: Restore tests dependencies
      run: dotnet restore ./ExtraChessTests/ExtraChessTests.csproj
    - name: Build engine
      run: dotnet build ./ExtraChess/ExtraChess.csproj --no-restore
    - name: Build tests
      run: dotnet build ./ExtraChessTests/ExtraChessTests.csproj --no-restore
    - name: Test
      run: dotnet test ./ExtraChessTests/ExtraChessTests.csproj --no-build --verbosity normal
